# Generated by Django 5.2.7 on 2025-10-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='article_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='guarantee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
