# Generated by Django 5.2.7 on 2025-10-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_products_article_number_products_guarantee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='article_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
